<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /var/www/html/sandbox/sites/default/files/civicrm/ext/biz.jmaconsulting.multilingualmailing/xml/schema/CRM/Multilingualmailing/MultilingualMailing.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:9cb9f7f75f38396c87b3853bd007e330)
 */

/**
 * Database access object for the MultilingualMailing entity.
 */
class CRM_Multilingualmailing_DAO_MultilingualMailing extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_multilingual_mailing';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique MultilingualMailing ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Mailing
   *
   * @var int
   */
  public $mailing_id;

  /**
   * FK to Mailing
   *
   * @var int
   */
  public $frenchmail_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_multilingual_mailing';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'frenchmail_id', 'civicrm_mailing', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Multilingualmailing_ExtensionUtil::ts('Unique MultilingualMailing ID'),
          'required' => TRUE,
          'where' => 'civicrm_multilingual_mailing.id',
          'table_name' => 'civicrm_multilingual_mailing',
          'entity' => 'MultilingualMailing',
          'bao' => 'CRM_Multilingualmailing_DAO_MultilingualMailing',
          'localizable' => 0,
        ],
        'mailing_id' => [
          'name' => 'mailing_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Multilingualmailing_ExtensionUtil::ts('FK to Mailing'),
          'where' => 'civicrm_multilingual_mailing.mailing_id',
          'table_name' => 'civicrm_multilingual_mailing',
          'entity' => 'MultilingualMailing',
          'bao' => 'CRM_Multilingualmailing_DAO_MultilingualMailing',
          'localizable' => 0,
        ],
        'frenchmail_id' => [
          'name' => 'frenchmail_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Multilingualmailing_ExtensionUtil::ts('FK to Mailing'),
          'where' => 'civicrm_multilingual_mailing.frenchmail_id',
          'table_name' => 'civicrm_multilingual_mailing',
          'entity' => 'MultilingualMailing',
          'bao' => 'CRM_Multilingualmailing_DAO_MultilingualMailing',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'multilingual_mailing', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'multilingual_mailing', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
